applicantapp/urls.py
"""
Urls for applicant
"""
from django.urls import path

from applicantapp.views import ProfileView, ResumeList, CreateResume, UpdateResume


app_name = 'applicantapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    # path('resume-list', ResumeList.as_view(), name='resume-list'),
    path('createresume', CreateResume.as_view(), name='createresume'),
    path('resume-list', ProfileView.as_view(), name='resume-list'),
    path('resumes-list/update_resume/<int:pk>/', UpdateResume.as_view(), name='update_resume'),
]

companyapp/urls.py
from django.urls import path

from .views import (
    ProfileView, CompanyDetailView, CompanyUpdateView, JobCreateView,
    JobUpdateView, JobListView, ResumeListHR, ResumeListDetail
    )


app_name = 'companyapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/card/', CompanyDetailView.as_view(), name='card'),
    path('<int:pk>/card/edit/', CompanyUpdateView.as_view(), name='edit'),
    path('<int:pk>/job/new/', JobCreateView.as_view(), name='new-job'),
    path('job/<int:pk>/edit/', JobUpdateView.as_view(), name='edit-job'),
    path('job-list/', JobListView.as_view(), name='job-list'),
    path('resume-list/', ResumeListHR.as_view(), name='resume-list'),
    path('resume-detail/<int:pk>/', ResumeListDetail.as_view(), name='resume-list-detail'),
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
]

applicantapp/models.py
"""
Models for applicant
"""

from django.db import models

from authapp.models import MyUser


class StatusResume(models.Model):
    class Meta:
        verbose_name = 'Статус Резюме'
        verbose_name_plural = 'Статусы Резюме'

    status_name = models.CharField(max_length=250, blank=True, null=True)

    def __repr__(self):
        return self.status_name

    def __str__(self):
        return self.status_name


class Resume(models.Model):
    """
    Applicants resume
    """
    def user_directory_path(instance, filename):
        return f'resume/user_{instance.user.id}/{filename}'

    class Meta:
        get_latest_by = '-updated_at'
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'

    EMPLOYMENT_CHOICES = (
        ('FT', 'Полная занятость'),
        ('PT', 'Частичная занятость'),
        ('PW','Проектная работа'),
        ('VL','Волонтерство'),
        ('WP','Стажировка'),
    )

    WORK_SCHEDULE_CHOICES = (
        ('FD', 'Полный день'),
        ('SSCH', 'Сменный график'),
        ('FSCH', 'Гибкий график'),
        ('RW', 'Удаленная работа'),
        ('RBW', 'Вахтовый метод'),
    )

    EDUCATION_CHOICES = (
        ('SECONDARY', 'Среднее'),
        ('SPECIAL_SECONDARY','Среднее специальное'),
        ('UNFINISHED_HIGHER','Неоконченное высшее'),
        ('HIGHER', 'Высшее'),
        ('BACHELOR','Бакалавр'),
        ('MASTER', 'Магистр'),
        ('CANDIDATE', 'Кандидат наук'),
        ('DOCTOR', 'Доктор наук'),
    )

    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255, blank=False, verbose_name='Заголовок')
    first_name = models.CharField(max_length=255, blank=False, verbose_name='Имя')
    surname = models.CharField(max_length=255, blank=False, verbose_name='Фамилия')
    salary = models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемая заработная плата')
    date_of_birth = models.DateField(blank=False, verbose_name='Дата рождения')
    is_active = models.BooleanField(blank=False, default=False, verbose_name='Резюме активно')
    is_cheked = models.BooleanField(blank=False, default=False, verbose_name='Резюме проверенно модератором')
    city = models.CharField(max_length=255, blank=False, verbose_name='Город')
    user_pic = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name='Фото')
    links = models.CharField(max_length=255, blank=True, null=True, verbose_name='Ссылка на профиль в соц. сетях или сайт')
    employment = models.CharField(max_length=20, blank=False, choices=EMPLOYMENT_CHOICES, default='FT', verbose_name='Занятость')
    work_schedule = models.CharField(max_length=20, blank=False, choices=WORK_SCHEDULE_CHOICES, default='FD', verbose_name='График работы')
    education_type = models.CharField(max_length=20, blank=False, choices=EDUCATION_CHOICES, default='HIGHER', verbose_name='Образование')
    about_me = models.TextField(blank=True, null=True, verbose_name='Обо мне')
    key_skills = models.CharField(max_length=255, blank=True, null=True, verbose_name='Ключевые навыки')
    phone = models.CharField(max_length=20, blank=False, verbose_name='Телефон')
    moder_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')
    views_count = models.PositiveIntegerField(blank=False, default=0, verbose_name='Кол-во просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.ForeignKey(to=StatusResume, on_delete=models.DO_NOTHING, default=1, blank=True)

    def __repr__(self):
        return self.headline

    def __str__(self):
        return self.headline


class Education(models.Model):
    """
    Applicant education institutions
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Образовательное учреждение'
        verbose_name_plural = 'Образовательные учреждения'

    resume = models.ForeignKey(to=Resume, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False, verbose_name='Название учреждения')
    specialization = models.CharField(max_length=255, blank=False, verbose_name='Специальность')
    year_of_ending = models.PositiveIntegerField(blank=False, verbose_name='Год окончания')

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name


class Experience(models.Model):
    """
    Applicant work experience
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыт работы'

    resume = models.ForeignKey(to=Resume, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255, blank=False, verbose_name='Название компании')
    company_link = models.CharField(max_length=255, blank=True, null=True, verbose_name='Сайт компании')
    position = models.CharField(max_length=255, blank=False, verbose_name='Дожность')
    data_from = models.DateField(blank=False, verbose_name='Дата начала работы')
    data_to = models.DateField(blank=False, verbose_name='Дата окончания работы')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __repr__(self):
        return self.company_name

    def __str__(self):
        return self.company_name

applicantapp/forms.py
import django.forms as forms

from applicantapp.models import Resume


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Resume
        # fields = '__all__'
        exclude = ['user', 'is_cheked', 'moder_comment', 'created_at', 'updated_at', 'views_count',]

class ResumeUpdateForm(forms.ModelForm):
    class Meta:
        model = Resume
        exclude = ['user', 'is_cheked', 'moder_comment']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

applicantapp/views.py
"""
Views of applicant
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from applicantapp.forms import UserProfileForm, ResumeUpdateForm
from applicantapp.models import Resume, StatusResume
from authapp.models import MyUser


class ProfileView(LoginRequiredMixin, TemplateView):
    """
    ЛК Соискателя
    """
    template_name = 'applicantapp/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resume_list'] = Resume.objects.filter(user=self.request.user.pk)
        return context


class ResumeList(LoginRequiredMixin, ListView):
    """
    Список резюме пользователя
    """
    def get_queryset(self):
        return Resume.objects.filter(user=self.request.user.id)


class CreateResume(LoginRequiredMixin, CreateView):
    """
    Создание резюме
    """
    form_class = UserProfileForm
    template_name = 'applicantapp/create_resume.html'

    def get_success_url(self):
        print(self.object.id)
        return reverse_lazy('applicantapp:profile',args=(self.request.user.id,))

    def get_context_data(self, **kwargs):
        ctx = super(CreateResume, self).get_context_data(**kwargs)
        return ctx

    def form_valid(self, form):
        user_for_reg = MyUser.objects.get(id=self.request.user.id)
        form.instance.user = user_for_reg
        if form.data['submit_btn_val']:
            name_status = form.data['submit_btn_val']
            status_val = StatusResume.objects.get(id=name_status)
            form.instance.status = status_val
        return super(CreateResume, self).form_valid(form)

    # def from_invalid(self, form):
    #     text=form
    #     ic(form)
    #     return super(CreateResume, self).from_invalid(form)
    #
    def post(self, request, **kwargs):
        request.POST = request.POST.copy()
        return super(CreateResume, self).post(request, **kwargs)

class UpdateResume(LoginRequiredMixin, UpdateView):
    """
    Update Resume
    """
    model = Resume
    form_class = ResumeUpdateForm
    template_name = 'applicantapp/update_resume.html'
    success_url = '/'

templates/applicantapp/create_resume.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}

    {% block nav %}
        {#                {% include 'inc/nav.html' %}#}
    {% endblock %}

    {% block content %}
        <div class="container resume-container">

            <form method="post" id="form_for_post" class="form-resume" enctype="multipart/form-data"> {% csrf_token %}
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input class="form-control" placeholder="Заголовок" name="headline" maxlength="255" required
                               id="id_headline">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            <input class="form-control" placeholder="Имя" name="first_name" maxlength="255" required
                                   id="id_first_name">
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            <input class="form-control" placeholder="Фамилия" name="surname" maxlength="255" required
                                   id="id_surname">
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input type="number" min="0" class="form-control" placeholder="Желаемая заработная плата"
                               name="salary" maxlength="255"
                               id="id_salary">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input type="date" class="form-control" placeholder="Дата рождения" name="date_of_birth"
                               required
                               id="id_date_of_birth">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <div class="wrapper">
                        <span class="form-control middle">
                            <span class=""> Резюме активно  </span>
                            <input type="checkbox" class="" placeholder="Резюме активно" name="is_active"
                                   id="id_is_active">
                        </span>
                        </div>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            <input class="form-control" placeholder="Город" name="city" maxlength="255"
                                   id="id_city">
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Фото:</i></span>

                            <input type="file" class="form-control middle foto-file" id="id_user_pic" name="user_pic"
                                   accept="image/*">

                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input class="form-control" placeholder="Ссылка на профиль в соц. сетях или сайт" name="links"
                               maxlength="255" id="id_links">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Занятость:</i></span>
                            <select class="form-control" name="employment" id="id_employment">
                                <option value="FT" selected>Полная занятость</option>
                                <option value="PT">Частичная занятость</option>
                                <option value="PW">Проектная работа</option>
                                <option value="VL">Волонтерство</option>
                                <option value="PT">Стажировка</option>
                            </select>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i> Образование:</span>
                            <select class="form-control" name="education_type" id="id_education_type">
                                <option value="SECONDARY" selected>Среднее</option>
                                <option value="SPECIAL_SECONDARY">Среднее специальное</option>
                                <option value="UNFINISHED_HIGHER">Неоконченное высшее</option>
                                <option value="HIGHER">Высшее</option>
                                <option value="BACHELOR">Бакалавр</option>
                                <option value="MASTER">Магистр</option>
                                <option value="CANDIDATE">Кандидат наук</option>
                                <option value="DOCTOR">Доктор наук</option>
                            </select>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i> График работы:</span>
                        <select class="form-control" name="work_schedule" id="id_work_schedule">
                            <option value="FD" selected>Полный день</option>
                            <option value="SSCH">Сменный график</option>
                            <option value="FSCH">Гибкий график</option>
                            <option value="RW">Удаленная работа</option>
                            <option value="RBW">Вахтовый метод</option>
                        </select>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <textarea rows="4" id="id_about_me" class="form-control" placeholder="Обо мне" name="about_me">
                        </textarea>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input class="form-control" placeholder="Ключевые наваки" maxlength="255" name="key_skills"
                               id="id_key_skills">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <input class="form-control" placeholder="Телефон" maxlength="20" name="phone"
                               id="id_phone">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div>{% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                {% endif %}
                </div>


                <div class="row">
                    <div class="form-group col-lg-12" style="text-align: center;">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            <button type="submit" class="btn btn-gray btn-save" name="submit_btn_val" value="1">
                                Создать
                            </button>
                            <button type="submit" class="btn btn-gray btn-save" name="submit_btn_val" value="2">
                                Черновик
                            </button>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    {% endblock %}

    {% block js %} {{ block.super }}
        <script defer src="{% static 'js/create_resume.js' %}"></script>
    {% endblock %}

{% endblock %}

templates/applicantapp/resume_list.html
{% for resume in resume_list %}
   <div class="col-xs-12">
      <div class="item-block">
            <div class="hgroup">
                <h5>{{ resume.headline }} </h5>
                <h4>{{ resume.surname }} {{ resume.first_name }} </h4>

            </div>
         <div class="header-meta">
            <span class="location"><i class="fa fa-map-marker"></i> {{ resume.city }} </span><br>
            <span class="rate">{{ resume.salary }} руб. </span>
             <a href="{% url 'applicantapp:update_resume' resume.pk %}">Редактировать</a>
         </div>

      </div>
   </div>
{% endfor %}

templates/applicantapp/update_resume.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}

    {% block nav %}
        {#                {% include 'inc/nav.html' %}#}
    {% endblock %}

    {% block content %}
        <div class="container resume-container">
            <form method="post" class="form-resume" enctype="multipart/form-data"> {% csrf_token %}
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {{ form.headline }}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            {{ form.first_name }}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            {{ form.surname }}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {% if form.salary.value %}
                        {{ form.salary }}
                        {% else %}
                        <input type="number" min="0" class="form-control" placeholder="Желаемая заработная плата"
                               name="salary" maxlength="255"
                               id="id_salary">
                        {% endif %}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {{ form.date_of_birth }}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        <div class="wrapper">
                        <span class="form-control middle">
                            <span class=""> Резюме активно  </span>
                            <input type="checkbox" class="" placeholder="Резюме активно" name="is_active"
                                   id="id_is_active">
                        </span>
                        </div>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            {{ form.city }}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Фото:</i></span>
                            {% if form.user_pic.value %}
                            {{ form.user_pic }}
                            {% else %}
                            <input type="file" class="form-control middle foto-file" id="id_user_pic" name="user_pic" accept="image/*">
                            {% endif %}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {% if form.links.value %}
                        {{ form.links }}
                        {% else %}
                        <input class="form-control" placeholder="Ссылка на профиль в соц. сетях или сайт" name="links"
                               maxlength="255" id="id_links">
                        {% endif %}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Занятость:</i></span>
                            {{ form.employment }}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i> Образование:</span>
                            {{ form.education_type }}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i> График работы:</span>
                        {{ form.work_schedule }}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {% if form.about_me.value %}
                        {{ form.about_me }}
                        {% else %}
                        <textarea rows="4" id="id_about_me" class="form-control" placeholder="Обо мне" name="about_me">
                        </textarea>
                        {% endif %}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {% if form.key_skills.value %}
                        {{ form.key_skills }}
                        {% else %}
                        <input class="form-control" placeholder="Ключевые наваки" maxlength="255" name="key_skills"
                               id="id_key_skills">
                        {% endif %}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {{ form.phone }}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            {% if form.created_at.value %}
                            {{ form.created_at }}
                            {% else %}
                            <span class="form-control middle" id="id_created_at"> Дата создания    </span>
                            {% endif %}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
                            {% if form.updated_at.value %}
                            {{ form.updated_at }}
                            {% else %}
                            <span class="form-control middle" id="id_updated_at"> Дата обновления   </span>
                            {% endif %}
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class=""></i></span>
                        {{ form.views_count }}
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>

                </div>

                <div>{% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                {% endif %}
                </div>
                <input type="submit" class="btn-gray btn-save" value="Сохранить">
            </form>
        </div>
    {% endblock %}

{% endblock %}