companyapp/urls.py
from django.urls import path

from .views import (
    ProfileView, CompanyDetailView, CompanyUpdateView, JobCreateView,
    JobUpdateView, JobListView, ResumeListHR, ResumeListDetail
    )


app_name = 'companyapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/card/', CompanyDetailView.as_view(), name='card'),
    path('<int:pk>/card/edit/', CompanyUpdateView.as_view(), name='edit'),
    path('<int:pk>/job/new/', JobCreateView.as_view(), name='new-job'),
    path('job/<int:pk>/edit/', JobUpdateView.as_view(), name='edit-job'),
    path('job-list/', JobListView.as_view(), name='job-list'),
    path('resume-list/', ResumeListHR.as_view(), name='resume-list'),
    path('resume-detail/<int:pk>/', ResumeListDetail.as_view(), name='resume-list-detail'),
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
]

applicantapp/models.py
"""
Models for applicant
"""

from django.db import models

from authapp.models import MyUser


class StatusResume(models.Model):
    class Meta:
        verbose_name = 'Статус Резюме'
        verbose_name_plural = 'Статусы Резюме'

    status_name = models.CharField(max_length=250, blank=True, null=True)

    def __repr__(self):
        return self.status_name

    def __str__(self):
        return self.status_name


class Resume(models.Model):
    """
    Applicants resume
    """
    def user_directory_path(instance, filename):
        return f'resume/user_{instance.user.id}/{filename}'

    class Meta:
        get_latest_by = '-updated_at'
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'

    EMPLOYMENT_CHOICES = (
        ('FT', 'Полная занятость'),
        ('PT', 'Частичная занятость'),
        ('PW','Проектная работа'),
        ('VL','Волонтерство'),
        ('WP','Стажировка'),
    )

    WORK_SCHEDULE_CHOICES = (
        ('FD', 'Полный день'),
        ('SSCH', 'Сменный график'),
        ('FSCH', 'Гибкий график'),
        ('RW', 'Удаленная работа'),
        ('RBW', 'Вахтовый метод'),
    )

    EDUCATION_CHOICES = (
        ('SECONDARY', 'Среднее'),
        ('SPECIAL_SECONDARY','Среднее специальное'),
        ('UNFINISHED_HIGHER','Неоконченное высшее'),
        ('HIGHER', 'Высшее'),
        ('BACHELOR','Бакалавр'),
        ('MASTER', 'Магистр'),
        ('CANDIDATE', 'Кандидат наук'),
        ('DOCTOR', 'Доктор наук'),
    )

    user = models.ForeignKey(to=MyUser, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255, blank=False, verbose_name='Заголовок')
    first_name = models.CharField(max_length=255, blank=False, verbose_name='Имя')
    surname = models.CharField(max_length=255, blank=False, verbose_name='Фамилия')
    salary = models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемая заработная плата')
    date_of_birth = models.DateField(blank=False, verbose_name='Дата рождения')
    is_active = models.BooleanField(blank=False, default=False, verbose_name='Резюме активно')
    is_cheked = models.BooleanField(blank=False, default=False, verbose_name='Резюме проверенно модератором')
    city = models.CharField(max_length=255, blank=False, verbose_name='Город')
    user_pic = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name='Фото')
    links = models.CharField(max_length=255, blank=True, null=True, verbose_name='Ссылка на профиль в соц. сетях или сайт')
    employment = models.CharField(max_length=20, blank=False, choices=EMPLOYMENT_CHOICES, default='FT', verbose_name='Занятость')
    work_schedule = models.CharField(max_length=20, blank=False, choices=WORK_SCHEDULE_CHOICES, default='FD', verbose_name='График работы')
    education_type = models.CharField(max_length=20, blank=False, choices=EDUCATION_CHOICES, default='HIGHER', verbose_name='Образование')
    about_me = models.TextField(blank=True, null=True, verbose_name='Обо мне')
    key_skills = models.CharField(max_length=255, blank=True, null=True, verbose_name='Ключевые навыки')
    phone = models.CharField(max_length=20, blank=False, verbose_name='Телефон')
    moder_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')
    views_count = models.PositiveIntegerField(blank=False, default=0, verbose_name='Кол-во просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    status = models.ForeignKey(to=StatusResume, on_delete=models.DO_NOTHING, default=1, blank=True)

    def __repr__(self):
        return self.headline

    def __str__(self):
        return self.headline


class Education(models.Model):
    """
    Applicant education institutions
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Образовательное учреждение'
        verbose_name_plural = 'Образовательные учреждения'

    resume = models.ForeignKey(to=Resume, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False, verbose_name='Название учреждения')
    specialization = models.CharField(max_length=255, blank=False, verbose_name='Специальность')
    year_of_ending = models.PositiveIntegerField(blank=False, verbose_name='Год окончания')

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name


class Experience(models.Model):
    """
    Applicant work experience
    """

    class Meta:
        get_latest_by = '-id'
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыт работы'

    resume = models.ForeignKey(to=Resume, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255, blank=False, verbose_name='Название компании')
    company_link = models.CharField(max_length=255, blank=True, null=True, verbose_name='Сайт компании')
    position = models.CharField(max_length=255, blank=False, verbose_name='Дожность')
    data_from = models.DateField(blank=False, verbose_name='Дата начала работы')
    data_to = models.DateField(blank=False, verbose_name='Дата окончания работы')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __repr__(self):
        return self.company_name

    def __str__(self):
        return self.company_name

companyapp/models.py
from django.db import models, transaction
from django.urls import reverse_lazy

from authapp.models import MyUser


class Company(models.Model):
    """
    Компания-работодатель
    """
    def user_directory_path(instance, filename):
        return f'logo/user_{instance.user.id}/{filename}'

    STATUS = (
        ('0', 'Отклонена модератором'),
        ('1', 'Заготовка'),
        ('2', 'На модерации'),
        ('3', 'Опубликована'),
        ('4', 'Черновик'),
        ('9', 'Удалена'),
    )

    user = models.OneToOneField(to=MyUser, on_delete=models.PROTECT, related_name='company', verbose_name="Пользователь")
    name = models.CharField('Наименование компании', max_length=255, blank=False, db_index=True)
    status = models.CharField('Статус', max_length=1, choices=STATUS, default='1', db_index=True)
    logo = models.ImageField('Логотип', upload_to=user_directory_path, blank=True, null=True)
    headline = models.CharField('Слоган', max_length=255, blank=True)
    short_description = models.CharField('Краткое описание', max_length=255, blank=False)
    detail = models.TextField('Подробное описание', blank=True)
    location = models.CharField('Местонахождение', max_length=255, blank=False, db_index=True)
    link = models.CharField('Ссылка на сайт / соц.сеть', max_length=255, blank=True)
    moder_comment = models.TextField('Заключение модератора', blank=False, default='Комментарий: ')
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)
    views_count = models.PositiveIntegerField('Число просмотров', default=0)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    def views_counter(self):
        """ Счетчик просмотров карточки компании """
        if Company.objects.filter(pk=self).exists():
            with transaction.atomic():
                self = Company.objects.get(id=self)
                self.views_count += 1
                self.save()


def create(instance):
    """
    Создание заготовки компании по сигналу вновь зарегистрированного работодателя
    """
    Company.objects.create(user=instance,)


class Job(models.Model):
    """
    Вакансии
    """
    STATUS = (
        ('0', 'Отклонена модератором'),
        ('1', 'Заготовка'),
        ('2', 'На модерации'),
        ('3', 'Опубликована'),
        ('4', 'Черновик'),
        ('5', 'Скрыта'),
        ('6', 'Закрыта'),
        ('9', 'Удалена'),
    )

    GRADE = (
        ('NO', ''),
        ('TR', 'Trainee'),
        ('JR', 'Junior'),
        ('MD', 'Middle'),
        ('SR', 'Senior'),
        ('TL', 'TeamLead'),
        ('TD', 'CTO'),
    )

    CATEGORY = (
        ('NO', ''),
        ('FLS', 'Full Stack'),
        ('FED', 'Front-end'),
        ('BED', 'Back-end'),
        ('SW', 'Software'),
        ('AI', 'AI & ML'),
        ('BD', 'Big Data'),
        ('AND', 'Android'),
        ('IOS', 'iOS'),
        ('IOT', 'IoT'),
        ('QA', 'QA Engineer'),
        ('GD', 'GameDev'),
        ('PJM', 'Project Manager'),
        ('PDM', 'Product Manager'),
    )

    EMPLOYMENT = (
        ('FT', 'Полная занятость'),
        ('PT', 'Частичная занятость'),
        ('PW', 'Проектная работа'),
        ('VL', 'Волонтерство'),
        ('WP', 'Стажировка'),
    )

    WORK_SCHEDULE = (
        ('FD', 'Полный день'),
        ('SSCH', 'Сменный график'),
        ('FSCH', 'Гибкий график'),
        ('RW', 'Удаленная работа'),
        ('RBW', 'Вахтовый метод'),
    )

    EXPERIENCE = (
        ('WE', 'Без опыта'),
        ('SM', 'До 1 года'),
        ('MD', '1-3 года'),
        ('BG', 'Более 3 лет'),
    )

    company = models.ForeignKey(to=Company, on_delete=models.PROTECT, related_name='jobs', verbose_name='Компания')
    status = models.CharField('Статус', max_length=1, choices=STATUS, default='1', db_index=True)
    grade = models.CharField('Классность', max_length=2, choices=GRADE, default='NO', db_index=True)
    category = models.CharField('Категория', max_length=3, choices=CATEGORY, default='NO', db_index=True)
    salary = models.PositiveIntegerField('Зарплата', null=True, blank=True, db_index=True)
    city = models.CharField('Город', max_length=255, blank=False, db_index=True)
    employment = models.CharField('Тип занятости', max_length=2, choices=EMPLOYMENT, default='FT', db_index=True)
    work_schedule = models.CharField('График работы', max_length=4, choices=WORK_SCHEDULE, default='FD', db_index=True)
    experience = models.CharField('Опыт работы', max_length=2, choices=EXPERIENCE, default='WE', db_index=True)
    short_description = models.CharField('Краткое описание', max_length=255, blank=False)
    description = models.TextField('Подробное описание', blank=True, null=True)
    skills = models.CharField('Навыки', max_length=255, blank=True)
    moder_comment = models.TextField('Заключение модератора', blank=False, default='Комментарий: ')
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField('Дата обновления', auto_now=True)
    views_count = models.PositiveIntegerField('Число просмотров', default=0)

    class Meta:
        ordering = ('status', '-created_at',)
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

    def __repr__(self):
        dev, category = (
            'Разработчик', self.get_category_display()
        ) if self.grade not in ['TL', 'TD'] else ('', '')
        grade = self.get_grade_display()
        return f'{grade} {category} {dev}'

    def __str__(self):
        dev, category = (
            'Разработчик', self.get_category_display()
        ) if self.grade not in ['TL', 'TD'] else ('', '')
        grade = self.get_grade_display()
        return f'{grade} {category} {dev}'

    def get_absolute_url(self):
        return reverse_lazy('companyapp:profile', args=[self.company.pk])

    def change_status(self, status):
        """ Смена статуса вакансии """
        with transaction.atomic():
            self = Job.objects.get(id=self)
            self.status = status
            self.save()

companyapp/views.py
"""
Views of company
"""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, TemplateView, UpdateView

from .models import Company, Job
from applicantapp.models import Resume


class ProfileView(LoginRequiredMixin, TemplateView):
    """ ЛК Компании """
    template_name = 'companyapp/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['object'] = Company.objects.get(pk==self.kwargs['pk'])
        return context


class CompanyDetailView(LoginRequiredMixin, DetailView):
    """ Карточка компании """
    model = Company

    def get(self, request, *args, **kwargs):
        """ Счётчик просмотров """
        Company.views_counter(self.kwargs['pk'])
        return super().get(self, request, *args, **kwargs)
        # TODO  исключить из счета владельца, чтобы избежать накрутки


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактор карточки компании """
    model = Company
    fields = ('name', 'logo', 'headline', 'short_description', 'detail', 'location', 'link',)

    def get_success_url(self):
        return reverse_lazy('companyapp:card', args=[self.object.pk])


class JobCreateView(LoginRequiredMixin, CreateView):
    """ Карточка вакансии (создание) """
    model = Job
    fields = ('status', 'grade', 'category', 'salary', 'city', 'employment', 'skills',
              'work_schedule', 'experience', 'short_description', 'description',)

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        return super().form_valid(form)


class JobUpdateView(LoginRequiredMixin, UpdateView):
    """ Редактор карточки вакансии """
    model = Job
    fields = ('status', 'grade', 'category', 'salary', 'city', 'employment', 'skills',
              'work_schedule', 'experience', 'short_description', 'description',)


class JobListView(LoginRequiredMixin, ListView):
    """
    Список вакансий пользователя
    """
    model = Job
    fields = '__all__'

    def get_queryset(self):
        try:
            company = self.request.user.company
        except Exception:
            return self.model.objects.none()

        return company.jobs


class ResumeListHR(LoginRequiredMixin, ListView):
    """
    Список резюме c пагинацией по 25 штук
    """
    model = Resume
    paginate_by = 25
    template_name = 'companyapp/resume_list_hr.html'

    def get_queryset(self):
        return Resume.objects.filter(is_active=1)
    
    
class ResumeListDetail(LoginRequiredMixin, DetailView):
    """
    Развернуть резюме подробнро
    """
    
    model = Resume

    template_name = 'companyapp/resume_detail.html'
    def get_queryset(self):
        return Resume.objects.filter(pk=self.kwargs['pk'])

templates/companyapp/company_detail-jobs.html
<section id="open-positions" class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Открытые вакансии</h2>
        </header>

        <div class="row item-blocks-connected">
            {% for job in jobs %}
            <!-- Job item -->
                {% if job.status == '3' %}
                    <div class="col-xs-12">
                        <a class="item-block" href="{% url 'companyapp:edit-job' job.pk %}">
                            <header>
                                {% if job.company.logo %}
                                <img src="{{ job.company.logo.url }}" alt="">
                                {% endif %}
                                <div class="hgroup">
                                    <h4>{{ job }}</h4>
                                    <h5>{{ job.company.name }}
                                        <span class="label label-success">{{ job.get_employment_display }}</span>
                                        <span class="label label-success">{{ job.get_work_schedule_display }}</span>
                                    </h5>
                                </div>
                                <time datetime="">{{ job.updated_at }}</time><br>
                                <time datetime="">{{ job.updated_at|timesince }}&nbsp;назад</time>
                            </header>

                            <div class="item-body">
                                <p>{{ job.short_description }}</p>
                            </div>

                            <footer>
                                <ul class="details cols-3">
                                    <li class="text-left">
                                        <i class="fa fa-map-marker"></i>
                                        <span>{{ job.city }}</span>
                                    </li>

                                    <li class="text-center">
                                        <span>Опыт:&nbsp;{{ job.get_experience_display }}</span>
                                    </li>

                                    <li class="text-right">
                                        <i class="fa fa-money"></i>&nbsp;
                                        {% if job.salary %}
                                        <span>{{ job.salary }} &nbsp;руб</span>
                                        {% else %}
                                        <span>З/п не указана</span>
                                        {% endif %}
                                    </li>
                                </ul>
                            </footer>
                        </a>
                    </div>
                {% endif %}
            <!-- END Job item -->
            {% endfor %}
        </div>
    </div>
</section>

templates/companyapp/company_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <header class="page-header bg-img size-lg">
        <div class="container">
            <div class="header-detail">
                {% if object.logo %}
                    <img class="logo" src="{{ object.logo.url }}" alt="">
                {% else %}
                    <img class="logo" src="{% static 'img/logo-default.png' %}" alt="">
                {% endif %}
                <div class="hgroup">
                    <h1>{{ object.name }}</h1>
                    <h3>{{ object.headline }}</h3>
                </div>
                <hr>
                <p class="lead">{{ object.short_description }}</p>
            
                <ul class="details cols-3">
                    <li class="text-left">
                        <i class="fa fa-map-marker"></i>
                        <span>{{ object.location }}</span>
                    </li>
                    <li class="text-center">
                        <i class="fa fa-globe"></i>
                        <a href="http://{{ object.link }}/">{{ object.link }}</a>
                    </li>
                    <li class="text-right">
                        <i class="fa fa-eye"></i>
                        <span>{{ object.views_count }}</span>
                    </li>
                </ul>

                {% if user.pk == object.user.pk %}
                    <div class="button-group">
                        <div class="action-buttons">
                            <a class="btn btn-primary" href="{% url 'companyapp:edit' object.pk %}">Редактировать карточку компании</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main container -->
    <main>
        <!-- Company detail -->
        <section>
            <div class="container">
                <header class="section-header">
                    <h2>О Компании</h2>
                </header>
                <p>{{ object.detail }}</p>       
            </div>
        </section>
        <!-- END Company detail -->

        <!-- Open positions -->
            {% include 'companyapp/company_detail-jobs.html' with jobs=object.jobs.select_related %}
        <!-- END Open positions -->

    </main>
    <!-- END Main container -->
{% endblock %}

{% block footer %} {% endblock %}

templates/companyapp/resume_detail.html
{#<h1>{{ object.headline }}</h1>#}
{#<p>{{ object.content }}</p>#}
{#<p>Reporter: {{ object.reporter }}</p>#}
{#<p>Published: {{ object.pub_date|date }}</p>#}
{#<p>Date: {{ now|date }}</p>#}


{% extends 'base.html' %}
{% load static %}

{% block body %}
    {% block header %}
        {% include 'inc/nav.html' %}
    {% endblock %}

    {% block nav %}
        {#                {% include 'inc/nav.html' %}#}
    {% endblock %}

    {% block content %}
        <div class="container resume-container">

                <div class="form-group">
                    <div class="input-group" style="text-align: center">
                        <span class="input-group-addon"><i class=""></i></span>
{#                        <span type="number" min="0" class="form-control form_control_centr_heigh"#}
{#                              id="id_salary">{{ object.salary }}</span>#}
                            <img src="/media/{{ object.user_pic }}" alt="Photo" height="150">
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Название</i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_headline"> {{ object.headline }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Имя</i></span>
                            <span class="form-control form_control_centr_heigh"
                                  id="id_first_name"> {{ object.first_name }}</span>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="">Фамилия</i></span>
                            <span class="form-control form_control_centr_heigh"
                                   id="id_surname">{{ object.surname  }}</span>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon">Желаемая заработная плата<i class=""></i></span>
                        <span type="number" min="0" class="form-control form_control_centr_heigh"
                              id="id_salary">{{ object.salary }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Дата рождения</i></span>
                        <span type="date" class="form-control form_control_centr_heigh"
                               id="id_date_of_birth">{{ object.date_of_birth }} </span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>
{##}
{#                <div class="form-group">#}
{#                    <div class="input-group">#}
{#                        <span class="input-group-addon"><i class=""></i></span>#}
{#                        <div class="wrapper">#}
{#                        <span class="form-control middle">#}
{#                            <span class=""> Резюме активно  </span>#}
{#                            <input type="checkbox" class="" placeholder="Резюме активно" name="is_active"#}
{#                                   id="id_is_active">#}
{#                        </span>#}
{#                        </div>#}
{#                        <span class="input-group-addon"><i class=""></i></span>#}
{#                    </div>#}
{#                </div>#}
{##}
                <div class="row">
                    <div class="form-group col-lg-6">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""> Город </i></span>
                            <span class="form-control form_control_centr_heigh"
                                  id="id_city"> {{ object.city }}</span>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>

{#                    <div class="form-group col-lg-6">#}
{#                        <div class="input-group">#}
{#                            <span class="input-group-addon"><i class="">Фото:</i></span>#}
{##}
{#                            <input type="file" class="form-control middle foto-file" id="id_user_pic" name="user_pic"#}
{#                                   accept="image/*">#}
{##}
{#                            <span class="input-group-addon"><i class=""></i></span>#}
{#                        </div>#}
{#                    </div>#}
                </div>
{##}
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon "><i class="">Ссылка на профиль в соц. сетях или сайт</i></span>
                        <span class="form-control form_control_centr_heigh"
                               id="id_links"> {{ object.links }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                 <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Занятость</i></span>
                        <span class="form-control form_control_centr_heigh"
                               id="id_employment"> {{ object.employment}}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Образование</i></span>
                        <span class="form-control form_control_centr_heigh"
                               id="id_education_type"> {{ object.education_type}}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">График работы:</i></span>
                        <span class="form-control form_control_centr_heigh"
                               id="id_work_schedule"> {{ object.work_schedule}}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Обо мне</i></span>
{#                        <textarea  rows="1" id="id_about_me"  placeholder="Обо мне" name="about_me" readonly>#}
{#                            {{ object.about_me }}#}
{#                        </textarea>#}
                        <span class="form-control form_control_centr_heigh"> {{ object.about_me }}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>


                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="">Телефон</i></span>
                        <span class="form-control form_control_centr_heigh"
                              id="id_phone">{{ object.phone}}</span>
                        <span class="input-group-addon"><i class=""></i></span>
                    </div>
                </div>

                <div>{% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                {% endif %}
                </div>

                <div class="row">
                    <div class="form-group col-lg-12" style="text-align: center;">
                        <div class="input-group">
                            <span class="input-group-addon"><i class=""></i></span>
{#                            <button type="submit" class="btn btn-gray btn-save" name="submit_btn_val" value="1">#}
{#                                Откликнуться#}
{#                            </button>#}
                            <button class="btn btn-gray">Пригласить</button>
                            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-gray"> Назад </a>
                            <span class="input-group-addon"><i class=""></i></span>
                        </div>
                    </div>
                </div>

        </div>

    {% endblock %}

    {% block js %} {{ block.super }}
        <script defer src="{% static 'js/create_resume.js' %}"></script>
    {% endblock %}

{% endblock %}