applicantapp/urls.py
"""
Urls for applicant
"""
from django.urls import path

from applicantapp.views import ProfileView, ResumeList, CreateResume, UpdateResume


app_name = 'applicantapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    # path('resume-list', ResumeList.as_view(), name='resume-list'),
    path('createresume', CreateResume.as_view(), name='createresume'),
    path('resume-list', ProfileView.as_view(), name='resume-list'),
    path('resumes-list/update_resume/<int:pk>/', UpdateResume.as_view(), name='update_resume'),
]

authapp/urls.py
from django.urls import path

from .views import SignUp, Login, Logout, forget_pass


app_name = 'authapp'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('forget-pass/', forget_pass, name='forget-pass'),
]

companyapp/urls.py
from django.urls import path

from .views import (
    ProfileView, CompanyDetailView, CompanyUpdateView, JobCreateView,
    JobUpdateView, JobListView, ResumeListHR, ResumeListDetail
    )


app_name = 'companyapp'

urlpatterns = [
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/card/', CompanyDetailView.as_view(), name='card'),
    path('<int:pk>/card/edit/', CompanyUpdateView.as_view(), name='edit'),
    path('<int:pk>/job/new/', JobCreateView.as_view(), name='new-job'),
    path('job/<int:pk>/edit/', JobUpdateView.as_view(), name='edit-job'),
    path('job-list/', JobListView.as_view(), name='job-list'),
    path('resume-list/', ResumeListHR.as_view(), name='resume-list'),
    path('resume-detail/<int:pk>/', ResumeListDetail.as_view(), name='resume-list-detail'),
]

mainapp/urls.py
from django.urls import path

from .views import Index


app_name = 'mainapp'

urlpatterns = [
    path('', Index.as_view(), name='index')
]

staff/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += [
    path(r'', include('mainapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('applicant/', include('applicantapp.urls')),
    path('company/', include('companyapp.urls')),
]

templates/inc/footer.html
<!-- Site footer -->
<footer class="site-footer">

    <!-- Top section -->
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6> О проекте </h6>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut repellendus rem nobis dolores ad exercitationem!
                    Culpa commodi ipsam totam nemo eaque, atque est consequatur unde earum, vitae tempora doloremque.
                    Voluptatem modi tempora quia consectetur nulla quos error sed ad odit nam, quae, voluptas cumque.
                </p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6> {{ title_name }} </h6>
                <ul class="footer-links">
                    <li><a href="#">О нас</a></li>
                    <li><a href="#">F.A.Q.</a></li>
                    <li><a href="#">Политика конфиденциальности</a></li>
                    <li><a href="#">Напишите нам</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Популярные направления</h6>
                <ul class="footer-links">
                    <li><a href="#">Front-end developer</a></li>
                    <li><a href="#">Android developer</a></li>
                    <li><a href="#">Python developer</a></li>
                    <li><a href="#">Full stack developer</a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <!-- END Top section -->

    <!-- Bottom section -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyrights &copy; 2021 All Rights Reserved by
                    <a href="#">GeekStaff</a>.
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a class="vk" href="#"><i class="fa fa-vk"></i></a></li>
                    <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                    <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END Bottom section -->

</footer>
<!-- END Site footer -->

templates/inc/header.html
<!-- Site header -->
<header class="site-header size-lg text-center">
    <div class="container">
        <div class="col-xs-12">
            <br><br>
            <h2>Мы предлагаем <mark>1,259</mark> IT-вакансий прямо сейчас!</h2>
            <h5 class="font-alt">Найдите работу мечты за минуту.</h5>
            <br><br>

            <form class="header-job-search">
                <div class="input-keyword">
                    <input type="text" class="form-control" placeholder="Профессия, навыки, компания">
                </div>

                <div class="input-location">
                    <input type="text" class="form-control" placeholder="Город">
                </div>

                <div class="btn-search">
                    <button class="btn btn-primary" type="submit">Поиск</button>
                    <a href="#">Расширенный поиск</a>
                </div>
            </form>
        </div>

        <!-- Facts -->
        <div class="row">
    
            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">1259</span></p>
                <h6>Вакансий</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">4502</span></p>
                <h6>Соискателей</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">9010</span></p>
                <h6>Резюме</h6>
            </div>

            <div class="counter col-md-3 col-sm-6">
                <p><span data-step="50" data-time="2500">212</span></p>
                <h6>IT-компаний</h6>
            </div>
    
        </div>
        <!-- END Facts -->
    </div>
</header>
<!-- END Site header -->

templates/inc/index-jobs.html
{% load static %}

<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Недавние вакансии</h2>
            <p>Последние предложения о работе, размещённые на сайте</p>
        </header>

        <div class="row item-blocks-connected">

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                        <div class="hgroup">
                            <h4>Сеньор Frontend разработчик</h4>
                            <h5>Google</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Калифорния</span>
                            <span class="label label-success">Полная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-linkedin.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>Software Engineer (Entry or Senior)</h4>
                            <h5>Linkedin</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Ливермор, Калифорния</span>
                            <span class="label label-success">Удалённо</span>
                            <span class="label label-warning">Частичная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-envato.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>FullStack Web разработчик</h4>
                            <h5>Envato</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Сан Франциско, Калифорния</span>
                            <span class="label label-info">Фриланс</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                        <div class="hgroup">
                            <h4>Web разработчик</h4>
                            <h5>Facebook</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Лексингтон, Массачусетс</span>
                            <span class="label label-danger">Стажировка</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->

            <!-- Job item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                        <div class="hgroup">
                            <h4>Сеньор SQL Server разработчик</h4>
                            <h5>Microsoft</h5>
                        </div>
                        <div class="header-meta">
                            <span class="location">Пало Альта, Калифорния</span>
                            <span class="label label-success">Удалённо</span>
                            <span class="label label-success">Полная занятость</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END Job item -->
            
        </div>
        <br /><br />
        <p class="text-center"><a class="btn btn-info" href="#">Больше вакансий</a></p>
    </div>
</section>

templates/inc/index-news.html
<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Последние Новости</h2>
            <p>Самая свежая информация из мира IT-рекрутинга</p>
        </header>

        <div class="row item-blocks-connected">
            
            <!-- News item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <div class="hgroup">
                            <h4>Срочные новости из кремниевой долины</h4>
                            <h5>Илон Маск планирует расширение компании во 2-м квартале год...</h5>
                        </div>
                        <div class="header-meta">
                            <div class="ti-time"> 05.03.21 09.21</div>
                            <span class="news label label-success">Подробнее...</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END News item -->

            <!-- News item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <div class="hgroup">
                            <h4>Очередные новости мира Frontend-а</h4>
                            <h5>В ходе очередной прошедшей конференции разработчиков, отме...</h5>
                        </div>
                        <div class="header-meta">
                            <div class="ti-time"> 04.03.21 16.40</div>
                            <span class="news label label-success">Подробнее...</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END News item -->

            <!-- News item -->
            <div class="col-xs-12">
                <a class="item-block" href="#">
                    <header>
                        <div class="hgroup">
                            <h4>Топ 15 трендов рекрутинга 2020 года</h4>
                            <h5>Самые современные подходы, которые значительно повлияют на...</h5>
                        </div>
                        <div class="header-meta">
                            <div class="ti-time"> 04.03.21 10.17</div>
                            <span class="news label label-success">Подробнее...</span>
                        </div>
                    </header>
                </a>
            </div>
            <!-- END News item -->

        </div>
        <br /><br />
        <p class="text-center"><a class="btn btn-info" href="#">Все новости</a></p>
    </div>
</section>

templates/inc/index-partners.html
{% load static %}

<section class="bg-alt">
    <div class="container">
        <header class="section-header">
            <h2>Наши партнёры</h2>
            <p>IT-Компании</p>
        </header>

        <div class="category-grid">

            <a href="#">
                <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                <h6>Google</h6>
                <p>Цель компании – упорядочить всю информацию и сделать ее доступной</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                <h6>Facebook</h6>
                <p>Give people the power to build community and bring the world closer together</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                <h6>Microsoft</h6>
                <p>Microsoft – обеспечивает продуктивность в мире, где царят мобильность и облако</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-microsoft.jpg' %}" alt="" />
                <h6>Microsoft</h6>
                <p>Microsoft – обеспечивает продуктивность в мире, где царят мобильность и облако</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-google.jpg' %}" alt="" />
                <h6>Google</h6>
                <p>Цель компании – упорядочить всю информацию и сделать ее доступной</p>
            </a>

            <a href="#">
                <img src="{% static 'img/logo-facebook.png' %}" alt="" />
                <h6>Facebook</h6>
                <p>Give people the power to build community and bring the world closer together</p>
            </a>

        </div>
        <p class="text-center"><a class="btn btn-info" href="#">Посмотреть всех партнёров</a></p>
    </div>
</section>

templates/inc/nav-menu.html
<ul class="nav-menu">
    <li>
        <a href="#">Вакансии</a>
        <ul>
            <li><a href="#">Поиск вакансий</a></li>
            <li><a href="#">Подробная вакансия</a></li>
            <li><a href="#">Разместить вакансию</a></li>
            <li><a href="{% url 'companyapp:job-list'%}">Управление вакансиями</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Резюме</a>
        <ul>
            <li><a href="#">Поиск резюме</a></li>
            <li><a href="{% url 'companyapp:resume-list'%}">Список резюме</a></li>
            <li><a href="{% url 'applicantapp:createresume'%}">Создать резюме</a></li>
            <li><a href="{% url 'applicantapp:resume-list'%}">Управление резюме</a></li>
        </ul>
    </li>
    <li>
        <a href="#">IT-Компании</a>
        <ul>
            <li><a href="#">Найти IT-компанию</a></li>
            <li><a href="#">Описание компании</a></li>
            <li><a href="#">Создать компанию</a></li>
            <li><a href="#">Управление компаниями</a></li>
        </ul>
    </li>
    <li>
        <a href="#">Информация</a>
        <ul>
            <li><a href="#">О нас</a></li>
            <li><a href="#">Контакты</a></li>
            <li><a href="#">F.A.Q.</a></li>
        </ul>
    </li>
</ul>

templates/inc/nav.html
{% load static %}

<!-- Navigation bar -->
<nav class="navbar">
    <div class="container">

        <!-- Logo -->
        <div class="pull-left">
            <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

            <div class="logo-wrapper">
                <a class="logo" href="{% url 'mainapp:index' %}"><img src="{% static 'img/logo1.png' %}" alt="logo"></a>
            </div>
        </div>
        <!-- END Logo -->

        <!-- User account -->
        <div class="pull-right">
            <div class="dropdown user-account">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    <img src="{% static 'img/logo-ava.jpg' %}" alt="avatar">
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    {% if user.is_authenticated %}
                        <li style="padding-left:8px"> {{ user.email }} </li>
                        {% if user.is_superuser %} <li><a href="/admin/">Админка</a></li> {% endif %}
                        {% if user.is_staff %} <li><a href="#">Модерировать</a></li> {% endif %}
                        {% if user.role == 'HR' %} 
                            <li><a href="{% url 'companyapp:profile' user.pk %}">Личный кабинет</a></li> 
                        {% endif %}
                        {% if user.role == 'REC' and not user.is_staff %} 
                            <li><a href="{% url 'applicantapp:profile' user.pk %}">Личный кабинет</a></li> 
                        {% endif %}
                        <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'authapp:login' %}">Войти</a></li>
                        <li><a href="{% url 'authapp:signup' %}">Регистрация</a></li>
                        <li><a href="{% url 'authapp:forget-pass' %}">Забыли пароль?</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- END User account -->

        <!-- Navigation menu -->
        {% include 'inc/nav-menu.html' %}
        <!-- END Navigation menu -->
    </div>
</nav>